# Generated by Django 5.0 on 2023-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=500)),
                ('initial_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('ai_message', models.TextField()),
            ],
        ),
    ]
