# Generated by Django 5.0 on 2023-12-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/')),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('face_book', models.URLField(max_length=500)),
                ('twitter', models.URLField(max_length=500)),
                ('youtube', models.URLField(max_length=500)),
                ('instagram', models.URLField(max_length=500)),
                ('linkedin', models.URLField(max_length=500)),
            ],
        ),
    ]
